import { Roboto, Nunito } from 'next/font/google';
import type { Metadata } from "next";
// import localFont from "next/font/local";

import "./globals.css";

const roboto_sans = Roboto({
  subsets: ["latin"],
  style: ['normal', 'italic'],
  variable: "--font-roboto-sans",
  display: 'swap',
  weight: ["100", "300", "400", "500", "700", "900"]
});
const nunito_sans = Nunito({
  subsets: ["latin"],
  style: ['normal', 'italic'],
  variable: "--font-nunito-sans",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${roboto_sans.variable} ${nunito_sans.variable}`}>
        {children}
      </body>
    </html>
  );
}
